language: generic
sudo: required

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - docker-compose build

before_script:
  # - docker-compose run --rm --no-deps web echo 'Gems now pre-installed.'
  - docker-compose run --rm --no-deps web bundle exec rails db:test:prepare

script:
  - docker-compose run web bundle exec rspec

after_script:
  - docker-compose down
