language: generic
sudo: required

services:
  - docker

before_script:
  - docker restart
  - docker-compose build
  - docker-compose run web bundle exec rails db:test:prepare

script:
  - docker-compose run web bundle exec rspec
