sudo: required
services:
  - docker
install:
  - gem uninstall bundler
  - gem install bundler --version '2.0.2'

scripts:
  - gem install bundler:2.0.2
  - docker build . -t smonetti/kube
  - docker images smonetti/kube
