language: generic
sudo: required

services:
  - docker

before_install:
  - sudo service postgresql stop
  - docker -v
  - docker-compose -v

install:
  - docker-compose build

before_script:
  - docker-compose run web bundle exec rails db:test:prepare

script:
  - docker-compose run web bundle exec rspec

after_script:
  - docker-compose down
